apiVersion: v1
kind: Service
metadata: 
  name: golang-ci-cd
spec:
  selector:
    app: golang-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer